apiVersion: v1
kind: PersistentVolume
metadata:
  name: theresa-wiki-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/minikube

