apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  serviceName: "envoy-ingress"
  template:
    metadata:
      labels:
        app: envoy
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      tolerations:
        - key: ingress
          operator: Exists
          effect: NoSchedule
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.25-latest
          env:
            - name: ENVOY_UID
              value: "0"
          ports:
            - name: https
              containerPort: 443
              hostPort: 443
          volumeMounts:
            - name: theresa-wiki-tls-secret
              mountPath: /cert/
              readOnly: true
            - name: envoy-conf
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 10m
              memory: 50M
      volumes:
        - name: theresa-wiki-tls-secret
          secret:
            secretName: theresa-wiki-tls-secret
            items:
              - key: tls.crt
                path: theresa.wiki.crt
              - key: tls.key
                path: theresa.wiki.key
        - name: envoy-conf
          configMap:
            name: envoy
            items:
              - key: envoy.yaml
                path: envoy.yaml
      priorityClassName: theresa-wiki-priority-critical
