apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-config
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-config
  serviceName: "nfs-config"
  template:
    metadata:
      labels:
        role: nfs-config
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      tolerations:
        - key: "ingress"
          operator: "Exists"
          effect: "NoSchedule"
      initContainers:
        - name: rclone-init
          image: rclone/rclone
          command: ["/bin/sh", "-c"]
          args:
            - rclone config touch;
              rclone config create gcs gcs service_account_file=/var/secrets/google/key.json --non-interactive;
              rclone copy gcs:theresa-wiki-k8s-configs /data;
              mkdir /theresa-ak-ab-runtime
          volumeMounts:
            - name: nfs-config
              mountPath: /data
            - name: gcs-theresa-wiki-k8s-configs-key
              mountPath: /var/secrets/google
      containers:
        - name: nfs-server
          image: gists/nfs-server:2.6.1
          env:
            - name: NFS_OPTION
              value: fsid=0,rw,sync,insecure,no_root_squash,no_subtree_check
          resources:
            limits:
              cpu: 50m
              memory: 50M
            requests:
              cpu: 5m
              memory: 20M
          ports:
            - name: nfs
              containerPort: 2049
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /nfs-share
              name: nfs-config
        - name: rclone
          image: rclone/rclone
          command: ["/bin/sh", "-c", "--"]
          args:
            - rclone config touch;
              rclone config create gcs gcs service_account_file=/var/secrets/google/key.json --non-interactive;
              while true;
              do rclone copy /nfs-share gcs:theresa-wiki-k8s-configs --exclude=rclone_cache/** --gcs-bucket-policy-only && sleep 6h;
              done;
          volumeMounts:
            - mountPath: /nfs-share
              name: nfs-config
            - name: gcs-theresa-wiki-k8s-configs-key
              mountPath: /var/secrets/google
      volumes:
        - name: nfs-config
          emptyDir:
            sizeLimit: 50Mi
        - name: gcs-theresa-wiki-k8s-configs-key
          secret:
            secretName: gcs-theresa-wiki-k8s-configs
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-config
spec:
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
  selector:
    role: nfs-config
