apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  serviceName: "nfs-server"
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      tolerations:
        - key: "ingress"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: nfs-server
          image: gists/nfs-server:2.6.1
          env:
            - name: NFS_OPTION
              value: fsid=0,rw,async,insecure,no_root_squash,no_subtree_check
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 5m
              memory: 20M
          ports:
            - name: nfs
              containerPort: 2049
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /nfs-share
              name: theresa-wiki-pvc
      volumes:
        - name: theresa-wiki-pvc
          persistentVolumeClaim:
            claimName: theresa-wiki-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
  selector:
    role: nfs-server
