apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx-ingress"
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      containers:
        - name: nginx
          image: "nginx"
          ports:
            - name: https
              containerPort: 443
              hostPort: 443
            - name: http
              containerPort: 80
              hostPort: 80
          volumeMounts:
            - name: theresa-wiki-tls-secret
              mountPath: /cert
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: nginx-cache-data
              mountPath: /data/nginx/cache
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 10m
              memory: 20M
      volumes:
        - name: theresa-wiki-tls-secret
          secret:
            secretName: theresa-wiki-tls-secret
            items:
              - key: tls.crt
                path: theresa.wiki.crt
              - key: tls.key
                path: theresa.wiki.key
        - name: nginx-conf
          configMap:
            name: nginx
            items:
              - key: default-conf
                path: nginx.conf
        - name: nginx-cache-data
          emptyDir: {}
