apiVersion: apps/v1
kind: Deployment
metadata:
  name: theresa-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      role: theresa-frontend
  template:
    metadata:
      labels:
        role: theresa-frontend
    spec:
      containers:
        - name: theresa-frontend
          image: gcr.io/theresa-wiki/theresa-frontend:latest
          resources:
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://redis.default.svc.cluster.local:6379
            - name: THERESA_STATIC
              value: static.theresa.wiki
            - name: THERESA_S3
              value: s3.default.svc.cluster.local
---
kind: Service
apiVersion: v1
metadata:
  name: theresa-frontend
spec:
  ports:
    - name: theresa-frontend
      port: 3000
  selector:
    role: theresa-frontend
