apiVersion: apps/v1
kind: Deployment
metadata:
  name: theresa-go
spec:
  replicas: 1
  selector:
    matchLabels:
      role: theresa-go
  template:
    metadata:
      labels:
        role: theresa-go
    spec:
      containers:
        - name: theresa-go
          image: us-central1-docker.pkg.dev/theresa-wiki/theresa-wiki-docker-registry/theresa-go:latest
          resources:
            limits:
              cpu: 500m
              memory: 300M
            requests:
              cpu: 200m
              memory: 200M
          ports:
            - name: theresa-go
              containerPort: 8000
          volumeMounts:
            - mountPath: /app/AK_AB_DATA
              name: theresa-wiki-ak-ab
          env:
            - name: THERESA_GO_REDIS_DSN
              value: redis://redis.default.svc.cluster.local:6379/1
            - name: GOOGLE_DRIVE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: theresa-go-config
                  key: GOOGLE_DRIVE_CLIENT_ID
            - name: GOOGLE_DRIVE_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: theresa-go-config
                  key: GOOGLE_DRIVE_CLIENT_SECRET
            - name: GOOGLE_DRIVE_REFRESH_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: theresa-go-config
                  key: GOOGLE_DRIVE_REFRESH_TOKEN
            - name: GOOGLE_DRIVE_ROOT_FOLDER_ID
              valueFrom:
                configMapKeyRef:
                  name: theresa-go-config
                  key: GOOGLE_DRIVE_ROOT_FOLDER_ID
            - name: GOOGLE_DRIVE_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: theresa-go-config
                  key: GOOGLE_DRIVE_TOKEN
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: theresa-wiki-ak-ab
          persistentVolumeClaim:
            claimName: theresa-wiki-ak-ab-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: theresa-go
spec:
  clusterIP: None
  ports:
    - name: theresa-go
      port: 8000
      targetPort: 8000
  selector:
    role: theresa-go
---
kind: Service
apiVersion: v1
metadata:
  name: s3
spec:
  ports:
    - name: theresa-go
      port: 80
      targetPort: 8000
  selector:
    role: theresa-go
