apiVersion: batch/v1
kind: CronJob
metadata:
  name: theresa-ak-ab-cron
spec:
  schedule: "*/3 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: theresa-ak-ab-spot-invoker
          nodeSelector:
            cloud.google.com/gke-nodepool: default-pool
          containers:
            - name: theresa-ak-ab-cron
              image: gcr.io/theresa-wiki/theresa-ak-ab:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: SPOT_INVOKER
                  value: "TRUE"
                - name: GP_PROXY
                  value: http://mitmproxy.default.svc.cluster.local:8080
                - name: REDIS_DSN
                  value: redis://redis.default.svc.cluster.local:6379/2
              volumeMounts:
                - mountPath: /app/AK_AB_DATA
                  name: theresa-wiki-ak-ab
                - mountPath: /app/configs
                  name: theresa-wiki-configs-ak-ab
                  subPath: theresa-ak-ab
                - mountPath: /app/logs/ak_ab
                  name: theresa-wiki-ak-ab-logs
                - mountPath: /app/runtime
                  name: theresa-wiki-configs-ak-ab
                  subPath: theresa-ak-ab-runtime
          restartPolicy: OnFailure
          volumes:
            - name: theresa-wiki-ak-ab
              persistentVolumeClaim:
                claimName: theresa-wiki-ak-ab-pvc
            - name: theresa-wiki-configs-ak-ab
              persistentVolumeClaim:
                claimName: theresa-wiki-configs-pvc
            - name: theresa-wiki-ak-ab-logs
              emptyDir: {}
