apiVersion: apps/v1
kind: Deployment
metadata:
  name: theresa-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      role: theresa-frontend
  template:
    metadata:
      labels:
        role: theresa-frontend
    spec:
      containers:
        - name: theresa-frontend
          image: us-central1-docker.pkg.dev/theresa-wiki/theresa-wiki-docker-registry/theresa-frontend:latest
          resources:
            limits:
              cpu: 500m
              memory: 750M
            requests:
              cpu: 200m
              memory: 200M
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://redis.default.svc.cluster.local:6379/0
            - name: THERESA_STATIC
              value: https://static.theresa.wiki
            - name: THERESA_S3
              value: http://s3.default.svc.cluster.local/api/v0/AK/CN/Android/assets/smart/unpacked_assetbundle/assets/torappu/dynamicassets/gamedata/
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /api/startup
              port: 3000
            failureThreshold: 30
            periodSeconds: 30
            timeoutSeconds: 5
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      priorityClassName: theresa-wiki-priority-frontend
---
kind: Service
apiVersion: v1
metadata:
  name: theresa-frontend
spec:
  clusterIP: None
  ports:
    - name: theresa-frontend
      port: 3000
      targetPort: 3000
  selector:
    role: theresa-frontend
