apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: envoy
  name: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  serviceName: envoy-ingress
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - env:
            - name: ENVOY_UID
              value: "0"
          image: envoyproxy/envoy:v1.25-latest
          name: envoy
          ports:
            - containerPort: 443
              hostPort: 443
              name: https
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 10m
              memory: 50M
          volumeMounts:
            - mountPath: /cert/
              name: theresa-wiki-tls-secret
              readOnly: true
            - mountPath: /etc/envoy/envoy.yaml
              name: envoy-conf
              readOnly: true
              subPath: envoy.yaml
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      priorityClassName: theresa-wiki-priority-critical
      tolerations:
        - effect: NoSchedule
          key: ingress
          operator: Exists
      volumes:
        - name: theresa-wiki-tls-secret
          secret:
            items:
              - key: tls.crt
                path: theresa.wiki.crt
              - key: tls.key
                path: theresa.wiki.key
            secretName: theresa-wiki-tls-secret
        - configMap:
            items:
              - key: envoy.yaml
                path: envoy.yaml
            name: envoy
          name: envoy-conf
