apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: mitmproxy
  template:
    metadata:
      labels:
        role: mitmproxy
    spec:
      containers:
        - command:
            - mitmdump
            - --set
            - stream_large_bodies=1
            - --flow-detail=4
          image: mitmproxy/mitmproxy:latest
          imagePullPolicy: Always
          name: mitmproxy
          ports:
            - containerPort: 8080
              name: mitmproxy-port
          resources:
            limits:
              cpu: 100m
              memory: 150M
            requests:
              cpu: 5m
              memory: 100M
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      priorityClassName: theresa-wiki-priority-low
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: ingress
          operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: mitmproxy
spec:
  ports:
    - name: mitmproxy-port
      port: 8080
      targetPort: 8080
  selector:
    role: mitmproxy
