apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-config
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-config
  serviceName: nfs-config
  template:
    metadata:
      labels:
        role: nfs-config
    spec:
      containers:
        - env:
            - name: NFS_OPTION
              value: fsid=0,rw,sync,insecure,no_root_squash,no_subtree_check
          image: gists/nfs-server:2.6.1
          name: nfs-server
          ports:
            - containerPort: 2049
              name: nfs
          resources:
            limits:
              cpu: 50m
              memory: 50M
            requests:
              cpu: 5m
              memory: 20M
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /nfs-share
              name: nfs-config
        - args:
            - rclone config touch -q;
              while true;
              do rclone copy /nfs-share :gcs,service_account_file=/var/secrets/google/key.json:/theresa-wiki-k8s-configs --exclude=rclone_cache/** --gcs-bucket-policy-only -vvv && sleep 6h;
              done;
          command: [/bin/sh, -c, --]
          image: rclone/rclone
          name: rclone
          volumeMounts:
            - mountPath: /nfs-share
              name: nfs-config
            - mountPath: /var/secrets/google
              name: gcs-theresa-wiki-k8s-configs-key
      initContainers:
        - args:
            - set -e;
              rclone config touch -q;
              rclone copy :gcs,service_account_file=/var/secrets/google/key.json:/theresa-wiki-k8s-configs /data -vvv;
              mkdir /data/theresa-ak-ab-runtime;
          command: [/bin/sh, -c]
          image: rclone/rclone
          name: rclone-init
          volumeMounts:
            - mountPath: /data
              name: nfs-config
            - mountPath: /var/secrets/google
              name: gcs-theresa-wiki-k8s-configs-key
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      priorityClassName: theresa-wiki-priority-critical
      tolerations:
        - effect: NoSchedule
          key: ingress
          operator: Exists
      volumes:
        - emptyDir:
            sizeLimit: 50Mi
          name: nfs-config
        - name: gcs-theresa-wiki-k8s-configs-key
          secret:
            secretName: gcs-theresa-wiki-k8s-configs
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-config
spec:
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
  selector:
    role: nfs-config
