apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  serviceName: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - env:
            - name: NFS_OPTION
              value: fsid=0,rw,async,insecure,no_root_squash,no_subtree_check
          image: gists/nfs-server:2.6.1
          name: nfs-server
          ports:
            - containerPort: 2049
              name: nfs
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 5m
              memory: 20M
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /nfs-share
              name: theresa-wiki-pvc
      nodeSelector:
        cloud.google.com/gke-nodepool: ingress-pool
      priorityClassName: theresa-wiki-priority-critical
      tolerations:
        - effect: NoSchedule
          key: ingress
          operator: Exists
      volumes:
        - name: theresa-wiki-pvc
          persistentVolumeClaim:
            claimName: theresa-wiki-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
  selector:
    role: nfs-server
