apiVersion: apps/v1
kind: Deployment
metadata:
  name: theresa-drive
spec:
  replicas: 1
  selector:
    matchLabels:
      role: theresa-drive
  template:
    metadata:
      labels:
        role: theresa-drive
    spec:
      containers:
        - image: xhofe/alist:latest
          imagePullPolicy: Always
          name: theresa-drive
          ports:
            - containerPort: 5244
              name: server
          resources:
            limits:
              cpu: 50m
              memory: 100M
            requests:
              cpu: 10m
              memory: 20M
          volumeMounts:
            - mountPath: /opt/alist/data
              name: theresa-wiki-configs-pvc-drive
              subPath: theresa-drive
      priorityClassName: theresa-wiki-priority-low
      volumes:
        - name: theresa-wiki-configs-pvc-drive
          persistentVolumeClaim:
            claimName: theresa-wiki-configs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: theresa-drive
spec:
  ports:
    - name: theresa-drive
      port: 5244
      targetPort: 5244
  selector:
    role: theresa-drive
