apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: theresa-go-hpa
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 200
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: theresa-go
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: theresa-frontend-hpa
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 200
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: theresa-frontend
