apiVersion: v1
kind: PersistentVolume
metadata:
  name: theresa-wiki-ak-ab-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.100.0.1
    path: "/AK_AB_DATA"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theresa-wiki-ak-ab-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: theresa-wiki-ak-ab-pv
