apiVersion: v1
kind: PersistentVolume
metadata:
  name: theresa-wiki-ak-ab-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Gi
  mountOptions:
    - nfsvers=4.2
    - noatime
  nfs:
    path: /AK_AB_DATA
    server: nfs-server.default.svc.cluster.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theresa-wiki-ak-ab-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: theresa-wiki-ak-ab-pv
