apiVersion: v1
kind: PersistentVolume
metadata:
  name: theresa-configs-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.100.0.1
    path: "/theresa-wiki-configs"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theresa-wiki-configs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi
  volumeName: theresa-configs-pv
