apiVersion: v1
kind: PersistentVolume
metadata:
  name: theresa-wiki-configs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Mi
  mountOptions:
    - nfsvers=4.2
    - noatime
  nfs:
    path: /
    server: nfs-config.default.svc.cluster.local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theresa-wiki-configs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: ""
  volumeName: theresa-wiki-configs-pv
