allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: theresa-wiki-standard
mountOptions:
  - noatime
  - noiversion
  - journal_checksum
  - journal_async_commit
  - data=writeback
  - inode_readahead_blks=4096
parameters:
  fstype: ext4
  replication-type: none
  type: pd-standard
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
