apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: kube-dns-vpa
  namespace: kube-system
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: kubedns
        minAllowed:
          cpu: 5m
  targetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: kube-dns
  updatePolicy:
    updateMode: Auto
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: fluentbit-gke-vpa
  namespace: kube-system
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: fluentbit-gke
  updatePolicy:
    updateMode: Auto
