apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: theresa-wiki-standard
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
allowVolumeExpansion: true
mountOptions:
  - noatime
reclaimPolicy: Retain
