apiVersion: v1
kind: PersistentVolume
metadata:
  name: theresa-wiki-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 225Gi
  gcePersistentDisk:
    fsType: ext4
    pdName: theresa-wiki-pv
  mountOptions:
    - noatime
    - noiversion
    - journal_checksum
    - journal_async_commit
    - data=writeback
    - nobarrier
    - discard
    - inode_readahead_blks=4096
  persistentVolumeReclaimPolicy: Retain
  storageClassName: theresa-wiki-standard
