apiVersion: v1
kind: PersistentVolume
metadata:
  name: theresa-wiki-pv
spec:
  storageClassName: theresa-wiki-standard
  capacity:
    storage: 225Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: theresa-wiki-pv
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime
    - noiversion
    - journal_checksum
    - journal_async_commit
    - data=writeback
    - nobarrier
    - discard
