apiVersion: v1
kind: PersistentVolume
metadata:
  name: theresa-wiki-pv
spec:
  storageClassName: theresa-wiki-standard
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: theresa-wiki-pv
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - noatime