apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default-conf: |
    worker_processes 5;

    events {}

    http {
      # This is needed to allow variables in proxy_pass directives, and bypass upstream startup checks
      # Variables must use the service FQDN <service>.<namespace>.svc.cluster.local
      resolver kube-dns.kube-system.svc.cluster.local valid=30s ipv6=off;

      # ssl
      ssl_certificate     theresa.wiki.crt;
      ssl_certificate_key theresa.wiki.key;

      # mimes
      include mime.types;
      default_type application/octet-stream;

      # logging
      access_log   /var/log/nginx/access.log;
      error_log    /var/log/nginx/error.log;

      index index.html;

      proxy_read_timeout 300;
      proxy_connect_timeout 300;
      proxy_send_timeout 300; 

      # cache
      proxy_cache_path /data/nginx/cache/theresa levels=1:2 keys_zone=theresa:10m;
      proxy_cache_path /data/nginx/cache/theresa-static levels=1:2 keys_zone=theresa-static:10m;
      proxy_cache_key "$scheme$request_method$host$request_uri";
      
      server { 
        listen 443 ssl;
        server_name theresa.wiki;
        
        # cache
        proxy_cache theresa;
        proxy_cache_valid 200 5m;
        add_header X-Cache-Status $upstream_cache_status;

        location ~ {
          proxy_pass http://theresa-frontend.default.svc.cluster.local:3000;
          # proxy_set_header Host $host;
        }
      }

      server { 
        listen 443 ssl;
        server_name static.theresa.wiki;

        # cache
        proxy_cache theresa-static;
        proxy_cache_valid 200 24h;
        add_header X-Cache-Status $upstream_cache_status;

        location ~ {
          proxy_pass http://theresa-go.default.svc.cluster.local:8000;
          proxy_set_header Host $host;
        }
      }

      server { 
        listen 443 ssl;
        server_name drive.theresa.wiki;
        
        location ^~ /dav {
          return 404;
        }

        location ~ {
          proxy_pass http://theresa-drive.default.svc.cluster.local:5244;
        }
      }
    }
