apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for no service pods only.
kind: PriorityClass
metadata:
  name: theresa-wiki-priority-default
value: 10000
---
apiVersion: scheduling.k8s.io/v1
description: "This priority class should be used for `redis`, `nfs-config`, `nfs-server` service pods only."
kind: PriorityClass
metadata:
  name: theresa-wiki-priority-critical
value: 19000
---
apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for `theresa-go` service pods only.
kind: PriorityClass
metadata:
  name: theresa-wiki-priority-go
value: 9990
---
apiVersion: scheduling.k8s.io/v1
description: This priority class should be used for `theresa-frontend` service pods only.
kind: PriorityClass
metadata:
  name: theresa-wiki-priority-frontend
value: 9980
---
apiVersion: scheduling.k8s.io/v1
description: "This priority class should be used for `theresa-drive`, `mitmproxy`, `theresa-ak-ab` service pods only."
kind: PriorityClass
metadata:
  name: theresa-wiki-priority-low
value: 1000
