apiVersion: v1
data:
  redis-config: |
    # Redis configuration
    # redis.conf is reference only
    bind * -::*
    protected-mode no
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    always-show-logo no
    set-proc-title yes
    proc-title-template "{title} {listen-addr} {server-mode}"
    save 3600 1
    save 300 100
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    maxmemory 125mb
    maxmemory-policy volatile-ttl
kind: ConfigMap
metadata:
  name: redis-config
